<?php

$this->load->helper("form");
echo '<table width="100%" border="0"><tr><td>';
echo form_open("canvasconfig");
echo "Bitte w&auml;hlen Sie ein Segel aus:<br><br>";
echo form_dropdown('scanvasid', $canvasarray, $selectedcanvas);
echo "<br>";
echo form_submit('choosecanvas', 'Segel auswählen');
echo form_submit('newcanvas', 'neues Segel anlegen');
echo "<br>";
echo "<br>";
echo '</td></tr></table>';

if (isset($newcanvasobject)) {
    echo '<table width="100%" border="0">';
    echo '<tr>';
    echo '<td width="200px">';
    echo 'Name des neuen Segel: ';
    echo '</td>';
    echo '<td>';
    echo form_input('canvasname', $newcanvasobject['name']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Segeltyp:';
    echo '</td>';
    echo '<td>';
    $js = 'onChange="this.form.submit();"';
    echo form_dropdown('ncanvastypeid', $canvastypeselect, $newcanvasobject['canvastypeid'], $js);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Zustand:';
    echo '</td>';
    echo '<td>';
    echo form_dropdown('sconditionid', $conditionselect, $newcanvasobject['conditionid']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Mast:';
    echo '</td>';
    echo '<td>';
    echo form_dropdown('smastid', $mastselect, $newcanvasobject['mastid']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo form_submit('savenewcanvas', 'Segel speichern');
    echo '</td>';
    echo '</tr>';
    echo '</table>';
}

if (isset($canvasobject)) {
    if ($editcanvas) {
        echo '<table width="100%" border="0">';
        echo '<tr>';
        echo '<td width="200px">';
        echo 'Name des Segel: ';
        echo '</td>';
        echo '<td>';
        echo form_input('canvasname', $canvasobject['name']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Segeltyp:';
        echo '</td>';
        echo '<td>';
        echo form_dropdown('scanvastypeid', $canvastypeselect, $selectedcanvastype);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Mast:';
        echo '</td>';
        echo '<td>';
        echo form_dropdown('smastid', $mastselect, $selectedmast);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Zustand:';
        echo '</td>';
        echo '<td>';
        echo $canvasobject['description'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo form_submit('savecanvas', 'Segel speichern');
        echo '</td>';
        echo '<td>';
        echo form_submit('deletecanvas', 'Segel löschen');
        echo '</td>';
        echo '</tr>';
        echo '</table>';
    } else {
        echo '<table width="100%" border="0">';
        echo '<tr>';
        echo '<td width="200px">';
        echo 'Name des Segel: ';
        echo '</td>';
        echo '<td>';
        echo $canvasobject['name'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Segeltyp:';
        echo '</td>';
        echo '<td>';
        echo $canvasobject['typename'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Mast:';
        echo '</td>';
        echo '<td>';
        echo $canvasobject['mastname'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Zustand:';
        echo '</td>';
        echo '<td>';
        echo $canvasobject['description'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo form_submit('editcanvas', 'Segel bearbeiten');
        echo '</td>';
        echo '</tr>';
        echo '</table>';
    }

    echo form_close();
}
?>
