<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->load->helper("form");
echo '<table width="100%" border="0"><tr><td>';
echo form_open("courseTypeConfig");
echo "Bitte wählen Sie einen Kurstyp aus:<br><br>";
echo form_dropdown('sCourseTypeID', $courseTypeArray, $selectedCourseType);
echo "<br>";
echo form_submit('chooseCourseType', 'Kurstyp auswählen');
echo form_submit('newCourseType', 'neuen Kurstyp anlegen');
echo "<br>";
echo "<br>";
echo '</td></tr></table>';

if (isset($newCourseTypeObject)) {
    echo '<table width="100%" border="0">';
    echo '<tr>';
    echo '<td width="200px">';
    echo 'Name neuer Kurstyp: ';
    echo '</td>';
    echo '<td>';
    echo form_input('courseTypeName', $newCourseTypeObject['typename']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Inhalt:';
    echo '</td>';
    echo '<td>';
    echo form_input('description', $newCourseTypeObject['description']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Kursdauer (Tage):';
    echo '</td>';
    echo '<td>';
    echo form_input('durationDays', $newCourseTypeObject['durationDays']);
//echo form_dropdown('sConditionID', $conditionSelect, null);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Kursdauer (Stunden):';
    echo '</td>';
    echo '<td>';
    echo form_input('durationHours', $newCourseTypeObject['durationHours']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Min. Teilnehmerzahl:';
    echo '</td>';
    echo '<td>';
    echo form_input('minParticipants', $newCourseTypeObject['minParticipants']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Max. Teilnehmerzahl:';
    echo '</td>';
    echo '<td>';
    echo form_input('maxParticipants', $newCourseTypeObject['maxParticipants']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'benötigtes Material:';
    echo '</td>';
    echo '<td>';
    echo form_dropdown('sBoatTypeID', $boatTypeSelect, NULL);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Anzahl Kursleiter:';
    echo '</td>';
    echo '<td>';
    echo form_input('numberOfCourseLeaders', $newCourseTypeObject['numberOfCourseLeaders']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Qualifikationen Kursleiter:';
    echo '</td>';
    echo '<td>';
    echo form_dropdown('sLicenseID', $licenseSelect, NULL);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Lohn Kursleiter:';
    echo '</td>';
    echo '<td>';
    echo form_input('salary', $newCourseTypeObject['salary']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Kurspreis in €:';
    echo '</td>';
    echo '<td>';
    echo form_input('price', $newCourseTypeObject['price']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Prüfungspreis in €:';
    echo '</td>';
    echo '<td>';
    echo form_input('priceExam', $newCourseTypeObject['priceExam']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo form_submit('saveNewCourseType', 'Kurstyp speichern');
    echo '</td>';
    echo '</tr>';
    echo '</table>';
}

if (isset($courseTypeObject)) {
    if ($editCourseType) {
        echo '<table width="100%" border="0">';
        echo '<tr>';
        echo '<td width="200px">';
        echo 'Name Kurstyp: ';
        echo '</td>';
        echo '<td>';
        echo form_input('courseTypeName', $courseTypeObject['c_typename']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Inhalt:';
        echo '</td>';
        echo '<td>';
        echo form_input('description', $courseTypeObject['description']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Tage):';
        echo '</td>';
        echo '<td>';
        echo form_input('durationDays', $courseTypeObject['durationDays']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Stunden):';
        echo '</td>';
        echo '<td>';
        echo form_input('durationHours', $courseTypeObject['durationHours']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Min. Teilnehmerzahl:';
        echo '</td>';
        echo '<td>';
        echo form_input('minParticipants', $courseTypeObject['minParticipants']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Max. Teilnehmerzahl:';
        echo '</td>';
        echo '<td>';
        echo form_input('maxParticipants', $courseTypeObject['maxParticipants']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'benötigtes Material:';
        echo '</td>';
        echo '<td>';
        echo form_dropdown('sBoatTypeID', $boatTypeSelect, $courseTypeObject['boatTypeID']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Anzahl Kursleiter:';
        echo '</td>';
        echo '<td>';
        echo form_input('numberOfCourseLeaders', $courseTypeObject['numberOfCourseLeaders']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Qualifikationen Kursleiter:';
        echo '</td>';
        echo '<td>';
        echo form_dropdown('sLicenseID', $licenseSelect, $courseTypeObject['licenseID']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Lohn Kursleiter:';
        echo '</td>';
        echo '<td>';
        echo form_input('salary', $courseTypeObject['salary']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kurspreis in €:';
        echo '</td>';
        echo '<td>';
        echo form_input('price', $courseTypeObject['price']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Prüfungspreis in €:';
        echo '</td>';
        echo '<td>';
        echo form_input('priceExam', $courseTypeObject['priceExam']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo form_submit('saveCourseType', 'Kurstyp speichern');
        echo '</td>';
        echo '</tr>';
        echo form_submit('deleteCourseType', 'Kurstyp löschen');
        echo '</table>';
    } else {
        echo '<table width="100%" border="0">';
        echo '<tr>';
        echo '<td width="200px">';
        echo 'Name Kurstyp: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['c_typename'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Inhalt: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['description'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Tage): ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['durationDays'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Stunden): ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['durationHours'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Min. Teilnehmerzahl: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['minParticipants'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Max. Teilnehmerzahl: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['maxParticipants'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'benötigtes Material: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['b_typename'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Anzahl Kursleiter: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['numberOfCourseLeaders'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Qualifikationen Kursleiter: ';
        echo '</td>';
        echo '<td>';
        //print_r($courseTypeObject);
        echo $courseTypeObject['name'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Lohn Kursleiter: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['salary'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kurspreis in €: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['price'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Prüfungspreis in €: ';
        echo '</td>';
        echo '<td>';
        echo $courseTypeObject['priceExam'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo form_submit('editCourseType', 'Kurstyp bearbeiten');
        echo '</td>';
        echo '</tr>';
        echo '</table>';
    }
}

echo form_close();




