<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->load->helper("form");
echo '<table width="100%" border="0"><tr><td>';
echo form_open("coursetypeconfig");
echo "Bitte wählen Sie einen Kurstyp aus:<br><br>";
echo form_dropdown('scoursetypeid', $coursetypearray, $selectedcoursetype);
echo "<br>";
echo form_submit('choosecoursetype', 'Kurstyp auswählen');
echo form_submit('newcoursetype', 'neuen Kurstyp anlegen');
echo "<br>";
echo "<br>";
echo '</td></tr></table>';

if (isset($newcoursetypeobject)) {
    echo '<table width="100%" border="0">';
    echo '<tr>';
    echo '<td width="200px">';
    echo 'Name neuer Kurstyp: ';
    echo '</td>';
    echo '<td>';
    echo form_input('coursetypename', $newcoursetypeobject['typename']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Inhalt:';
    echo '</td>';
    echo '<td>';
    echo form_input('description', $newcoursetypeobject['description']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Kursdauer (Tage):';
    echo '</td>';
    echo '<td>';
    echo form_input('durationdays', $newcoursetypeobject['durationdays']);
//echo form_dropdown('sConditionID', $conditionSelect, null);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Kursdauer (Stunden):';
    echo '</td>';
    echo '<td>';
    echo form_input('durationhours', $newcoursetypeobject['durationhours']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Min. Teilnehmerzahl:';
    echo '</td>';
    echo '<td>';
    echo form_input('minparticipants', $newcoursetypeobject['minparticipants']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Max. Teilnehmerzahl:';
    echo '</td>';
    echo '<td>';
    echo form_input('maxparticipants', $newcoursetypeobject['maxparticipants']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'benötigtes Material:';
    echo '</td>';
    echo '<td>';
    echo form_dropdown('sboattypeid', $boattypeselect, null);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Anzahl Kursleiter:';
    echo '</td>';
    echo '<td>';
    echo form_input('numberofcourseleaders', $newcoursetypeobject['numberofcourseleaders']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Qualifikationen Kursleiter:';
    echo '</td>';
    echo '<td>';
    echo form_dropdown('slicenseid', $licenseselect, null);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Lohn Kursleiter:';
    echo '</td>';
    echo '<td>';
    echo form_input('salary', $newcoursetypeobject['salary']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Kurspreis in €:';
    echo '</td>';
    echo '<td>';
    echo form_input('price', $newcoursetypeobject['price']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo 'Prüfungspreis in €:';
    echo '</td>';
    echo '<td>';
    echo form_input('priceexam', $newcoursetypeobject['priceexam']);
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>';
    echo form_submit('savenewcoursetype', 'Kurstyp speichern');
    echo '</td>';
    echo '</tr>';
    echo '</table>';
}

if (isset($coursetypeobject)) {
    if ($editcoursetype) {
        echo '<table width="100%" border="0">';
        echo '<tr>';
        echo '<td width="200px">';
        echo 'Name Kurstyp: ';
        echo '</td>';
        echo '<td>';
        echo form_input('coursetypename', $coursetypeobject['c_typename']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Inhalt:';
        echo '</td>';
        echo '<td>';
        echo form_input('description', $coursetypeobject['description']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Tage):';
        echo '</td>';
        echo '<td>';
        echo form_input('durationdays', $coursetypeobject['durationdays']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Stunden):';
        echo '</td>';
        echo '<td>';
        echo form_input('durationhours', $coursetypeobject['durationhours']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Min. Teilnehmerzahl:';
        echo '</td>';
        echo '<td>';
        echo form_input('minparticipants', $coursetypeobject['minparticipants']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Max. Teilnehmerzahl:';
        echo '</td>';
        echo '<td>';
        echo form_input('maxparticipants', $coursetypeobject['maxparticipants']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'benötigtes Material:';
        echo '</td>';
        echo '<td>';
        echo form_dropdown('sboattypeid', $boattypeselect, $coursetypeobject['boattypeid']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Anzahl Kursleiter:';
        echo '</td>';
        echo '<td>';
        echo form_input('numberofcourseleaders', $coursetypeobject['numberofcourseleaders']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Qualifikationen Kursleiter:';
        echo '</td>';
        echo '<td>';
        echo form_dropdown('slicenseid', $licenseselect, $coursetypeobject['licenseid']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Lohn Kursleiter:';
        echo '</td>';
        echo '<td>';
        echo form_input('salary', $coursetypeobject['salary']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kurspreis in €:';
        echo '</td>';
        echo '<td>';
        echo form_input('price', $coursetypeobject['price']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Prüfungspreis in €:';
        echo '</td>';
        echo '<td>';
        echo form_input('priceexam', $coursetypeobject['priceexam']);
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo form_submit('savecoursetype', 'Kurstyp speichern');
        echo '</td>';
        echo '</tr>';
        echo form_submit('deletecoursetype', 'Kurstyp löschen');
        echo '</table>';
    } else {
        echo '<table width="100%" border="0">';
        echo '<tr>';
        echo '<td width="200px">';
        echo 'Name Kurstyp: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['c_typename'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Inhalt: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['description'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Tage): ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['durationdays'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kursdauer (Stunden): ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['durationhours'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Min. Teilnehmerzahl: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['minparticipants'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Max. Teilnehmerzahl: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['maxparticipants'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'benötigtes Material: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['b_typename'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Anzahl Kursleiter: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['numberofcourseleaders'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Qualifikationen Kursleiter: ';
        echo '</td>';
        echo '<td>';
        //print_r($courseTypeObject);
        echo $coursetypeobject['name'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Lohn Kursleiter: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['salary'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Kurspreis in €: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['price'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo 'Prüfungspreis in €: ';
        echo '</td>';
        echo '<td>';
        echo $coursetypeobject['priceexam'];
        echo '</td>';
        echo '</tr>';
        echo '<tr>';
        echo '<td>';
        echo form_submit('editcoursetype', 'Kurstyp bearbeiten');
        echo '</td>';
        echo '</tr>';
        echo '</table>';
    }
}

echo form_close();




